### ISSUE TITLE
Authentification Rest

### ISSUE THREAD

**Issue by maninhat** [liuggio/symfony2-rest-api-the-best-2013-way#10]
It would be great, if you added user is authentication to the article.
One example for fos/userbundle - this is simple
And one for api key authentification

**Comment by inverse** [comment]
+1 for API key authentication

**Comment by liuggio** [comment]
I think the article is quite old now, I don't know if is sane to modify now. btw there's a group now about symfony and rest: https://groups.google.com/forum/#!topic/resting-with-symfony created by @willdurand
