### ISSUE TITLE
Inserting date issue using CURL from Terminal (JSON format)

### ISSUE THREAD

**Issue by kunjalpopat** [liuggio/symfony2-rest-api-the-best-2013-way#4]
Hello
we have used your rest api tutorial and all those are working fine,we have create new table and add date field on it, now when we have try to insert new record using curl from command line on that time we have problem in inserting date using following command

$curl -X POST -d '{"name":"testname","age":"25", "birthdate":"11-02-1991"}'  "Content-Type:application/json"

**Comment by liuggio** [comment]
it depends on how you have configured that field, usually the date is an ISO not a formatted string
